### ISSUE TITLE
Improve Pong Example

### ISSUE THREAD

**Issue by JohnDog3112** [twiddlingbits/twr-wasm#14]
* Remove any code that was only there for testing new d2d functions
* Make a standard 2 player Pong with a computer opponent
* Add sound effects as the AudioLibrary gets programmed
* Possibly add better physics like having paddle velocity affect the pong velocity

**Comment by twiddlingbits** [comment]
![image](https://github.com/user-attachments/assets/b0bf6f11-e18b-4033-b093-705095c0b51e)

**Comment by twiddlingbits** [comment]
The new pong update is awesome! 

On the 2 player pong, I have these suggestions:
1. Give the user instructions on what keys to use (i wasn't sure how to be player 2)
2. When the ball goes out of bound, before starting the new ball, give the user some kind of message.  See the original pong for what it did/said.
3. For bonus points (not sure its worth the effort): The original pong drew the score numbers out of graphics segments.  You are using a font.   Pong Purests will enjoy seeing an exact replica of the original game.

**Comment by twiddlingbits** [comment]
Audio is intermittent on Windows/Chrome.  I noted this in the audio issue.

**Comment by twiddlingbits** [comment]
i am leaving this open for the following:

1. Give the user instructions on what keys to use (i wasn't sure how to be player 2)
2. When the ball goes out of bound, before starting the new ball, give the user some kind of message. See the original pong for what it did/said.

But i am removing the must complete by milestone.

**Comment by JohnDog3112** [comment]
> 1. Give the user instructions on what keys to use (i wasn't sure how to be player 2)
For now, I've added a text box below the game canvas that gives instructions on what controls to use. I'm also considering making a short start screen that will display the controls as well so it's more obvious.

> 2. When the ball goes out of bound, before starting the new ball, give the user some kind of message. See the original pong for what it did/said. 
I'm looking at the Atari version of Pong and I don't see any message. The only difference I see is a slight delay until the ball spawns again.

Also, in the vein of displaying messages, I have been creating a class for centering text. When I did this, I moved a LinkedList generic class/struct over to extra.h which is shared between all of the pong files. However, I keep getting linking issues with it. Do you know what might be causing these?

clang -c -Wall -O3 --target=wasm32 -nostdinc -nostdlib -isystem  ../../include -I ../twr-cpp  pong-menu.cpp -o out/pong-menu.o
clang -c -Wall -O3 --target=wasm32 -nostdinc -nostdlib -isystem  ../../include -I ../twr-cpp  ../twr-cpp/canvas.cpp -o out/canvas.o
clang -c -Wall -O3 --target=wasm32 -nostdinc -nostdlib -isystem  ../../include -I ../twr-cpp  entry-point.cpp -o out/entry-point.o
clang -c -Wall -O3 --target=wasm32 -nostdinc -nostdlib -isystem  ../../include -I ../twr-cpp  pong.cpp -o out/pong.o
clang -c -Wall -O3 --target=wasm32 -nostdinc -nostdlib -isystem  ../../include -I ../twr-cpp  two-player-pong.cpp -o out/two-player-pong.o
clang -c -Wall -O3 --target=wasm32 -nostdinc -nostdlib -isystem  ../../include -I ../twr-cpp  extra.cpp -o out/extra.o
wasm-ld  out/pong-menu.o  out/canvas.o  out/entry-point.o  out/pong.o  out/two-player-pong.o  out/extra.o ../../lib-c/twr.a -o entry-point.wasm \
        --no-entry --initial-memory=2031616 --max-memory=2031616
wasm-ld: error: out/pong-menu.o: undefined symbol: LinkedListRoot<MenuButton>::LinkedListRoot()
wasm-ld: error: out/pong-menu.o: undefined symbol: LinkedListRoot<MenuButton>::addNode(MenuButton)
wasm-ld: error: out/pong-menu.o: undefined symbol: LinkedListRoot<MenuButton>::addNode(MenuButton)
wasm-ld: error: out/pong-menu.o: undefined symbol: LinkedListRoot<MenuButton>::addNode(MenuButton)
make: *** [Makefile:38: entry-point.wasm] Error 1

**Comment by twiddlingbits** [comment]
> I'm also considering making a short start screen

That seems like the way to go.

> I'm looking at the Atari version of Pong and I don't see any message.

Ok.  I am not that familiar with the original Pong.  But if you are doing what it does, then that's good.

> `However, I keep getting linking issues with it. Do you know what might be causing these?`

chatGPT says: https://chatgpt.com/share/66f9d97d-481c-800a-9372-c31f27465483

Here is what I wrote before I aske chatGPT, but I haven't really used templates in c++ (i do use them in typescript):

If you show me the code (commit it, or provide a link, or whatever), i can take a look.
But I will say that in the past whenever I have tried to put actual code in a .h file it has never ended well and I always end up putting it in a .cpp file (and the class detentions in a .h file, like canvas.cpp).  When it's in the .h, then you end up with name collision (same name compiled into multiple .o).  I think you can work around it with appropriate use of inline, but that seems to be very fragile and confusing.  I gave up getting it to work the one time i tried recently.  You could make the code static, which might avoid the collision.  But then you still have multiple copies of the same code, which doesn't seem clean, and there are probably other issues.

**Comment by twiddlingbits** [comment]
seems like this is fixed now.  Please close if you agree.
