### ISSUE TITLE
tests-d2d/*.jpg

### ISSUE THREAD

**Issue by twiddlingbits** [twiddlingbits/twr-wasm#17]
what is this line:

~~~
cp tests-d2d/*.jpg dist/tests-d2d
~~~

for in `buildbundle.sh` ?

**Comment by JohnDog3112** [comment]
This is to import the test image used for loadimage in the test cases. Importing an image from elsewhere gives cors errors when trying to get the canvas image data for generating the hash. Having it be a local image was the easiest fix, but I can try finding another solution if needed.

**Comment by twiddlingbits** [comment]
seems okay to me.
