### ISSUE TITLE
tests-d2d error in StrokeText

### ISSUE THREAD

**Issue by twiddlingbits** [twiddlingbits/twr-wasm#19]
I get this error running the tests-d2d:

`StrokeText test failed! Expected 0x6ECCA58D, 0xCB11F126, or 0xB954F57B got 0x1BAE7F1C`

**Comment by JohnDog3112** [comment]
This is one of those tests that might not work on other people's machines. I inserted 0xB954F57B for your computer, but I've now replaced it with 0x1BAE7F1C. Did any of the text-based tests break?

**Comment by twiddlingbits** [comment]
None of the other tests failed (just stroketext).  Now they all work fine.  Here is what stroke test looks like:

<img width="283" alt="image" src="https://github.com/user-attachments/assets/b5c3a561-569b-466a-96af-80de96f22174">

Assuming that is correct, please close this issue.
