### ISSUE TITLE
Async pong, background image renders outside of playfield

### ISSUE THREAD

**Issue by twiddlingbits** [twiddlingbits/twr-wasm#24]
Using Windows 11, Chrome:

<img width="729" alt="image" src="https://github.com/user-attachments/assets/94cdb9ba-6f0a-4422-a644-1b78b27f96af">

**Comment by twiddlingbits** [comment]
why do you use the term "dirty" (e.g. d2d_drawimagedirty ) ?

**Comment by twiddlingbits** [comment]
also, why is this needed?

~~~
   //clear everything outside to the right of the border (for when canvas is larger than play area)
   this->canvas.setFillStyleRGB(this->background_color);
   this->canvas.fillRect(this->width, 0.0, 200.0, this->height);
~~~

**Comment by JohnDog3112** [comment]
I mainly copied the syntax that was used for PutImage. Though I probably should come up with a better name.

The extra fill is needed because of the arc that’s drawn from the bottom left to the bottom right partially renders outside the border. Though, the fill area could be reduced.

**Comment by twiddlingbits** [comment]
putimagedirty uses "dirty" because that is the JS names of its extra parameters.  But I found those names confusing as used in that API.   dirty typically means cached data that needs to be written back.    If you look at the docs for drawImage, they don't use the term "dirty".   I think you could come up with a more clear name.

**Comment by twiddlingbits** [comment]
also don't forget to add any new functions (like d2d_drawimagedirty  to the d2d API Doc)
