### ISSUE TITLE
minor makefile issue in pong

### ISSUE THREAD

**Issue by twiddlingbits** [twiddlingbits/twr-wasm#46]
should the following be:

`rm -f out/*`

So as to clean the .js file?

~~~
clean:
	rm -f *.o
	rm -f *.wasm
	rm -f out/*.o
~~~

**Comment by JohnDog3112** [comment]
It should, I'll fix it in the next pull request.

**Comment by JohnDog3112** [comment]
I guess I forgot to mention it in the last PR, but I fixed it by changing the makefile to this:
~~~make
clean:
	rm -f *.wasm
	rm -f out/*
~~~
